name: Test and publish coverage to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          poetry install

      - name: run coverage
        run: poetry run pytest --cov=workflow --cov-report=term-missing --cov-report=html

      - name: upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/

      - name: Fix permissions and move coverage report
        run: |
          sudo chmod -R 777 htmlcov
          mkdir -p coverage-report
          cp -r htmlcov/* coverage-report/

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./coverage-report
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
